USE SONGDW

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'DimDate'))
BEGIN
	CREATE TABLE [dbo].[DimDate](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[AltId] [nvarchar](20) UNIQUE NOT NULL,
		[DayOfMonth] INT NOT NULL,
		[MonthOfYear] INT NOT NULL,
		[Year] INT NOT NULL
	)
END

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'DimPage'))
BEGIN
	CREATE TABLE [dbo].[DimPage](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[Name] [nvarchar](100) NOT NULL,
		[Home] [nvarchar](100) NOT NULL
	)
END

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'DimSinger'))
BEGIN
	CREATE TABLE [dbo].[DimSinger](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[Name] [nvarchar](100) NOT NULL
	)
END

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'DimPerformers'))
BEGIN
	CREATE TABLE [dbo].[DimPerformers](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[SingerId] [bigint] NOT NULL,
		[Name] [nvarchar](200) NULL,
		CONSTRAINT [UC_SingerId] UNIQUE NONCLUSTERED(
			[Id],
			[SingerId]
		)
	)
END

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'DimGenre'))
BEGIN
	CREATE TABLE [dbo].[DimGenre](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[Genre] [NVARCHAR](50) NOT NULL
	)
END

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'DimSong'))
BEGIN
	CREATE TABLE [dbo].[DimSong](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[SongId] [bigint] NOT NULL,
		[Title] [nvarchar](100) NOT NULL
	)
END

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'DimSongGenre'))
BEGIN
	CREATE TABLE [dbo].[DimSongGenre](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[GenreId] [bigint] NOT NULL,
		[Name] [nvarchar](500) NOT NULL,
		CONSTRAINT [UC_SongGenreId] UNIQUE NONCLUSTERED(
			[Id],
			[GenreId]
		)
	)
END

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
	WHERE TABLE_SCHEMA = 'dbo'
	AND  TABLE_NAME = 'FactSong'))
BEGIN
	CREATE TABLE [dbo].[FactSong](
		[Id] [bigint] PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[SongId] [bigint] NOT NULL,
		[DateId] [bigint] NOT NULL,
		[PerformersId] [bigint] NOT NULL,
		[SongGenreId] [bigint] NOT NULL,
		[TotalPlay] [int] NOT NULL
	)
END